title: Settings
data:
  site_name: 'David Keyes'
  social:
    -
      id: sSUoot4u
      name: Twitter
      url: 'https://twitter.com/dgkeyes'
      icon: site/social-icons/twitter.svg
    -
      id: vKTXb4SQ
      name: Github
      url: 'https://github.com/dgkeyes'
      icon: site/social-icons/github.svg
    -
      id: quhNUtBn
      name: Email
      url: 'mailto:david@rfortherestofus.com'
      icon: site/social-icons/email.svg
